const now = new Date("2026-01-01T00:00:00.000Z");

export const devProducts = [
  {
    id: 1,
    name: "Té Neurovegetativo",
    slug: "te-neurovegetativo",
    category: "fitoterapia" as const,
    shortDescription: "Infusión botánica para acompañar el equilibrio del sistema nervioso autónomo.",
    fullDescription:
      "Una fórmula de melisa, manzanilla, tilo y cáscara de naranja diseñada para apoyar rutinas de calma, descanso y autocuidado diario.",
    purpose: "Apoya la relajación, la pausa consciente y el bienestar general.",
    ingredients: ["Melissa officinalis", "Matricaria chamomilla", "Tilia europaea", "Citrus sinensis peel"],
    suggestedUse: "Preparar una taza por la mañana o al final de la tarde. Reposar de 5 a 7 minutos.",
    safetyNote: "Consultar a un profesional de salud antes de usar si está embarazada, en lactancia o toma medicamentos.",
    contraindications: "Hipersensibilidad a alguno de los componentes.",
    price: "185.00",
    currency: "GTQ",
    stock: 50,
    isActive: true,
    isFeatured: true,
    featuredImageUrl: "/products/te-neurovegetativo.jpg",
    createdAt: now,
    updatedAt: now,
    images: [],
  },
  {
    id: 2,
    name: "Infusión Somnium",
    slug: "infusion-somnium",
    category: "fitoterapia" as const,
    shortDescription: "Mezcla nocturna de hierbas para favorecer una rutina de descanso tranquila.",
    fullDescription:
      "Una infusión de uso nocturno formulada para acompañar el cierre del día y preparar al cuerpo para el descanso.",
    purpose: "Favorece la relajación nocturna y la calidad del descanso.",
    ingredients: ["Melissa officinalis", "Passiflora incarnata", "Matricaria chamomilla", "Lavandula angustifolia"],
    suggestedUse: "Tomar una taza 30 a 45 minutos antes de dormir.",
    safetyNote: "Puede causar somnolencia. Evitar conducir después de consumir.",
    contraindications: "Embarazo, lactancia, uso de sedantes o alergia a componentes.",
    price: "195.00",
    currency: "GTQ",
    stock: 40,
    isActive: true,
    isFeatured: true,
    featuredImageUrl: "/products/infusion-somnium.jpg",
    createdAt: now,
    updatedAt: now,
    images: [],
  },
  {
    id: 3,
    name: "Sachets Sensōris™",
    slug: "sachets-sensoris",
    category: "sachets" as const,
    shortDescription: "Sachets aromáticos botánicos para calma emocional y bienestar sensorial.",
    fullDescription:
      "Una sinergia aromática para escritorio, almohada o ritual de pausa, creada para acompañar momentos de calma.",
    purpose: "Bienestar olfativo, autocuidado sensorial y regulación emocional.",
    ingredients: ["Lavandula angustifolia", "Citrus aurantium amara", "Rosmarinus officinalis", "Mentha spicata"],
    suggestedUse: "Colocar cerca de la almohada, en el escritorio o en el bolso. Reemplazar cada 2 a 3 semanas.",
    safetyNote: "No ingerir. Mantener fuera del alcance de niños.",
    contraindications: "Alergia a componentes aromáticos o asma severa.",
    price: "125.00",
    currency: "GTQ",
    stock: 60,
    isActive: true,
    isFeatured: true,
    featuredImageUrl: "/products/sachets-sensoris.jpg",
    createdAt: now,
    updatedAt: now,
    images: [],
  },
  {
    id: 4,
    name: "Almohadillas Térmicas",
    slug: "almohadillas-termicas",
    category: "termoterapia" as const,
    shortDescription: "Almohadillas de hierbas para calor terapéutico, relajación muscular y confort local.",
    fullDescription:
      "Almohadillas rellenas de semillas y hierbas aromáticas que retienen calor suave para rutinas de descanso y tensión muscular.",
    purpose: "Termoterapia para relajación muscular y confort local.",
    ingredients: null,
    suggestedUse: "Calentar en microondas por 1 a 2 minutos y aplicar de 15 a 20 minutos.",
    safetyNote: "Verificar temperatura antes de aplicar. No usar sobre piel irritada.",
    contraindications: "Piel sensible, heridas abiertas o insensibilidad térmica.",
    price: "285.00",
    currency: "GTQ",
    stock: 25,
    isActive: true,
    isFeatured: true,
    featuredImageUrl: "/products/almohadillas-termicas.jpg",
    createdAt: now,
    updatedAt: now,
    images: [],
  },
  {
    id: 5,
    name: "Aceite NeuroMuscular",
    slug: "aceite-neuromuscular",
    category: "topicos" as const,
    shortDescription: "Aceite tópico para masaje, relajación muscular y confort localizado.",
    fullDescription:
      "Aceite portador con extractos botánicos y aceites esenciales para masaje externo en zonas de tensión.",
    purpose: "Relajación muscular y confort local por uso externo.",
    ingredients: ["Arnica montana", "Hypericum perforatum", "Mentha piperita", "Rosmarinus officinalis"],
    suggestedUse: "Aplicar una pequeña cantidad y masajear suavemente sobre la zona deseada.",
    safetyNote: "Uso externo únicamente. Evitar contacto con ojos y mucosas.",
    contraindications: "Embarazo, lactancia, piel sensible o alergia a componentes.",
    price: "220.00",
    currency: "GTQ",
    stock: 35,
    isActive: true,
    isFeatured: true,
    featuredImageUrl: "/products/aceite-neuromuscular.jpg",
    createdAt: now,
    updatedAt: now,
    images: [],
  },
  {
    id: 6,
    name: "Kit NeuroIntegrativo Fitociencia Care™",
    slug: "kit-neurointegrativo",
    category: "bundle" as const,
    shortDescription: "El protocolo completo con infusiones, sachets, termoterapia y aplicación tópica.",
    fullDescription:
      "Un kit de 8 semanas que reúne los componentes centrales del Modelo NeuroIntegrativo en una rutina guiada de bienestar.",
    purpose: "Protocolo completo de bienestar neurointegrativo.",
    ingredients: null,
    suggestedUse: "Seguir la guía de protocolo incluida durante 8 semanas.",
    safetyNote: "Revisar las contraindicaciones individuales de cada producto.",
    contraindications: "Ver contraindicaciones por producto.",
    price: "1450.00",
    currency: "GTQ",
    stock: 15,
    isActive: true,
    isFeatured: true,
    featuredImageUrl: "/products/kit-neurointegrativo.jpg",
    createdAt: now,
    updatedAt: now,
    images: [],
  },
  {
    id: 7,
    name: "InfusiÃ³n Digestum",
    slug: "infusion-digestum",
    category: "fitoterapia" as const,
    shortDescription: "Apoyo digestivo natural con plantas tradicionales para el eje intestino-cerebro.",
    fullDescription:
      "Una mezcla botÃ¡nica de boldo, hinojo y menta diseÃ±ada para acompaÃ±ar rutinas de bienestar digestivo despuÃ©s de las comidas.",
    purpose: "Apoya el bienestar digestivo y la sensaciÃ³n de ligereza.",
    ingredients: ["Peumus boldus", "Foeniculum vulgare", "Mentha piperita"],
    suggestedUse: "Preparar una taza despuÃ©s de las comidas principales.",
    safetyNote: "Consultar a un profesional de salud si tiene condiciones hepÃ¡ticas o toma medicamentos.",
    contraindications: "Embarazo, obstrucciÃ³n biliar o alergia a componentes.",
    price: "175.00",
    currency: "GTQ",
    stock: 45,
    isActive: true,
    isFeatured: false,
    featuredImageUrl: "/products/infusion-digestum.jpg",
    createdAt: now,
    updatedAt: now,
    images: [],
  },
  {
    id: 8,
    name: "Aceite de Ricino",
    slug: "aceite-ricino",
    category: "topicos" as const,
    shortDescription: "Aceite de ricino prensado en frÃ­o para rutinas de aplicaciÃ³n tÃ³pica lumbar.",
    fullDescription:
      "Aceite vegetal de uso externo, tradicionalmente integrado en compresas y protocolos de autocuidado corporal.",
    purpose: "AplicaciÃ³n tÃ³pica para protocolo de autocuidado lumbar.",
    ingredients: ["Ricinus communis"],
    suggestedUse: "Aplicar una capa fina sobre la zona lumbar y cubrir con paÃ±o de algodÃ³n.",
    safetyNote: "Uso externo Ãºnicamente. No aplicar sobre piel irritada o heridas abiertas.",
    contraindications: "Embarazo, piel rota o alergia al aceite de ricino.",
    price: "145.00",
    currency: "GTQ",
    stock: 30,
    isActive: true,
    isFeatured: false,
    featuredImageUrl: "/products/aceite-ricino.jpg",
    createdAt: now,
    updatedAt: now,
    images: [],
  },
];

export const devMembershipPlan = {
  id: 1,
  name: "Membresía Educativa Fitociencia Care™",
  slug: "membresia-educativa",
  description:
    "Acceso mensual a cursos, recursos descargables y contenido formativo para prevención, autocuidado y bienestar integrativo.",
  monthlyPrice: "299.00",
  currency: "GTQ",
  benefits: [
    "Acceso ilimitado a todos los cursos",
    "Materiales descargables",
    "Nuevos cursos cada mes",
    "Foro de comunidad",
    "Descuentos en productos",
  ],
  isActive: true,
  createdAt: now,
};

export const devCourses = [
  {
    id: 1,
    title: "Fundamentos de Fitoterapia Clínica",
    slug: "fundamentos-fitoterapia",
    description: "Principios activos, formas de uso, contraindicaciones y aplicaciones prácticas.",
    level: "beginner" as const,
    duration: "12 horas",
    instructor: "Equipo Fitociencia Care™",
    featuredImageUrl: null,
    requiresSubscription: true,
    price: null,
    isPublished: true,
    category: "fitoterapia" as const,
    createdAt: now,
    updatedAt: now,
    modules: [
      {
        id: 1,
        courseId: 1,
        title: "Bases clínicas",
        description: "Cómo leer una fórmula botánica con criterio de seguridad.",
        sortOrder: 1,
        createdAt: now,
        lessons: [
          { id: 1, title: "Introducción", slug: "introduccion", duration: "12 min", sortOrder: 1, isPreview: true },
          { id: 2, title: "Seguridad y contraindicaciones", slug: "seguridad", duration: "18 min", sortOrder: 2, isPreview: false },
        ],
      },
    ],
  },
  {
    id: 2,
    title: "Sistema Nervioso y Bienestar",
    slug: "sistema-nervioso-bienestar",
    description: "Estrategias naturales para acompañar el equilibrio del sistema nervioso autónomo.",
    level: "intermediate" as const,
    duration: "15 horas",
    instructor: "Equipo Fitociencia Care™",
    featuredImageUrl: null,
    requiresSubscription: true,
    price: null,
    isPublished: true,
    category: "sistema_nervioso" as const,
    createdAt: now,
    updatedAt: now,
    modules: [],
  },
  {
    id: 3,
    title: "Aromaterapia Científica",
    slug: "aromaterapia-cientifica",
    description: "Vía olfativa, sistema límbico y uso responsable de estímulos aromáticos.",
    level: "beginner" as const,
    duration: "8 horas",
    instructor: "Equipo Fitociencia Care™",
    featuredImageUrl: null,
    requiresSubscription: true,
    price: null,
    isPublished: true,
    category: "aromaterapia" as const,
    createdAt: now,
    updatedAt: now,
    modules: [],
  },
];

export const devBlogPosts = [
  {
    id: 1,
    title: "Melissa officinalis: la hierba de la calma",
    slug: "melissa-officinalis-hierba-calma",
    excerpt: "Propiedades de la melisa y su uso tradicional para acompañar procesos de relajación.",
    content:
      "La Melissa officinalis, conocida como toronjil o melisa, ha sido utilizada durante siglos en la tradición herbal europea.",
    featuredImageUrl: null,
    category: "fitoterapia" as const,
    tags: ["fitoterapia", "calma"],
    author: "Equipo Fitociencia Care™",
    seoTitle: null,
    seoDescription: null,
    isPublished: true,
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 2,
    title: "El eje intestino-cerebro y el bienestar diario",
    slug: "eje-intestino-cerebro-bienestar",
    excerpt: "Una mirada clara a la relación entre digestión, sistema nervioso y hábitos de autocuidado.",
    content:
      "El eje intestino-cerebro conecta señales digestivas, inmunológicas y nerviosas que influyen en el bienestar cotidiano.",
    featuredImageUrl: null,
    category: "eje_intestino_cerebro" as const,
    tags: ["digestión", "sistema nervioso"],
    author: "Equipo Fitociencia Care™",
    seoTitle: null,
    seoDescription: null,
    isPublished: true,
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 3,
    title: "Aromaterapia y sistema límbico",
    slug: "aromaterapia-sistema-limbico",
    excerpt: "Cómo los aromas pueden acompañar rutinas de calma a través del sistema olfativo.",
    content:
      "La vía olfativa ofrece una conexión directa entre estímulos aromáticos y respuesta emocional.",
    featuredImageUrl: null,
    category: "aromaterapia" as const,
    tags: ["aromaterapia", "emociones"],
    author: "Equipo Fitociencia Care™",
    seoTitle: null,
    seoDescription: null,
    isPublished: true,
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
  },
];

export const devResearchPosts = [
  {
    id: 1,
    title: "Fitoterapia en el apoyo al sistema nervioso autónomo",
    slug: "fitoterapia-sistema-nervioso-autonomo-revision",
    abstract: "Revisión de literatura sobre preparados botánicos y bienestar neurovegetativo.",
    content: "Resumen de evidencia disponible para uso educativo y no sustitutivo de atención médica.",
    pdfUrl: null,
    featuredImageUrl: null,
    author: "Equipo de Investigación Fitociencia Care™",
    category: "fitoterapia_clinica" as const,
    references: [],
    visibility: "public" as const,
    relatedProducts: [1, 6],
    relatedCourses: [1, 2],
    isPublished: true,
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
  },
];
